name: "godot-ci export"
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      deployBranch:
        description: 'Tag to deploy'
        required: true
        default: 'v0.0.1'

env:
  GODOT_VERSION: 4.3
  PROJECT: 1stsoldier/gmtk-2024
  TAG: ${{ inputs.deployBranch || github.ref_name }}

jobs:
    export-web:
        name: Web Export
        runs-on: ubuntu-20.04
        container:
          image: barichello/godot-ci:4.3
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              lfs: true
              persist-credentials: false
              ref: ${{ env.TAG }}

          - name: Setup Godot
            run: |
              mkdir -v -p ~/.local/share/godot/export_templates/
              mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

          - name: Web Build
            run: |
              mkdir -v -p build/web
              godot --headless --verbose --export-release "HTML5" ./build/web/index.html
            
          - name: Upload to Itch.io
            run: |
              butler -V
              butler push build/web/ ${PROJECT}:html5  --userversion 1.1.0 ${TAG}
              butler status ${PROJECT}:html5
            env:
              BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  
    